#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && cd ../../bin && pwd )"

FAULTS=0
FOLDER=$1

FAULT=$($DIR/phpmd $FOLDER text cleancode | wc -l)
FAULTS=$((FAULTS + FAULT)) 
echo "phpmd cleancode: $FAULT"

FAULT=$($DIR/phpmd $FOLDER text codesize | wc -l)
FAULTS=$((FAULTS + FAULT)) 
echo "phpmd codesize: $FAULT"

FAULT=$($DIR/phpmd $FOLDER text design | wc -l)
FAULTS=$((FAULTS + FAULT)) 
echo "phpmd design: $FAULT"

FAULT=$($DIR/phpmd $FOLDER text naming | wc -l)
FAULTS=$((FAULTS + FAULT)) 
echo "phpmd naming: $FAULT"

FAULT=$($DIR/phpmd $FOLDER text unusedcode | wc -l)
FAULTS=$((FAULTS + FAULT)) 
echo "phpmd unusedcode: $FAULT"

FAULT=$($DIR/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $FOLDER --report=summary | sed -n -r 's/A TOTAL OF (.*) ERROR.*AND (.*) WARNING.*/\1 + \2/p')
FAULT=$(echo $FAULT | bc)
FAULTS=$((FAULTS + FAULT))
echo "phpcs Drupal: $FAULT"

FAULT=$($DIR/phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $FOLDER --report=summary | sed -n -r 's/A TOTAL OF (.*) ERROR.*AND (.*) WARNING.*/\1 + \2/p')
FAULT=$(echo $FAULT | bc)
FAULTS=$((FAULTS + FAULT))
echo "phpcs DrupalPractice: $FAULT"

TOTAL=$($DIR/phploc --names=*.php,*.module,*.install,*.inc,*.js,*.scss $FOLDER | sed -n -r 's/.*\(NCLOC\) *(.*) \(.*\)/\1/p')
PERCENT=$(echo "scale=2; ($FAULTS / $TOTAL) * 100" | bc | sed -n -r 's/(.*)\..*/\1/p')
if [ -z $PERCENT ]
then
  PERCENT=0
fi  

echo "Total Faults: $FAULTS
Total Lines: $TOTAL
Quality Score: $PERCENT faults per 100 lines"
